#! /bin/sh

wget https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz
printf '%s\n%s\n%s\n%s\n%s\n' 'export PATH=$PATH:/usr/local/go/bin' 'export GOROOT=$HOME/go' 'export PATH=$PATH:$GOROOT/bin' 'export GOPATH=$GOROOT' 'export PATH=$PATH:$GOPATH/bin' >> file.txt

go get -u github.com/ipfs/ipfs-update
ipfs-update install v0.4.13-rc1

ipfs version

